theme: jekyll-theme-cayman
\documentclass[10pt,a4paper]{article}
%https://github.com/Abhilashkannan/latex-malayalam-article
\usepackage{geometry}
 \geometry{a4paper,total={150mm,237mm},left=30mm,top=30mm,}
\usepackage{fontspec}
\usepackage{polyglossia}
\usepackage{graphicx}
\setmainfont[
Script=Malayalam,
HyphenChar="00AD,
BoldFont=Gayathri-Bold.ttf,
ItalicFont=Gayathri-Thin.ttf,
]{Gayathri-Regular.ttf}

\setdefaultlanguage{malayalam}
\setotherlanguages{english}
\linespread{1.2}
\widowpenalty=10000
\clubpenalty=10000
\raggedbottom
\sloppy
\lefthyphenmin=3
\righthyphenmin=3
\title{\textbf{മലയാളം ആർട്ടിക്കിൾ മേക്കിങ് വീഡിയോ }}
\author{\textit{ ടൈപ്പ് ചെയ്തു പഠിക്കുന്നു  }}
\date{\today}

\begin{document}
 \Large
\maketitle
 
 \section{ഈ വർഷം 10 പുതിയ കാറുകളായി മേഴ്സിഡസ് ബെൻസ് ഇന്ത്യ......}
 
 കൊവിഡ് വാക്സിൻ പ്രതീക്ഷകൾക്ക് പുതുജീവൻ നൽകി ഓക്സ്ഫഡ് കൊവിഡ് വാക്സിൻ പരീക്ഷണം പുനഃരാരംഭിച്ചു. യുകെയിലെ വാക്സിൻ പരീക്ഷണമാണ് പുനഃരാരംഭിച്ചിരിക്കുന്നത്. നേരത്തെ വാക്സിൻ കുത്തിവച്ചയാൾക്ക് 'അജ്ഞാത അസുഖം' കണ്ടെത്തിയതിനെത്തുടർന്ന് നിർത്തിവെച്ച പരീക്ഷണമാണ് പുനഃരാരംഭിച്ചതെന്ന് ടൈംസ് ഓഫ് ഇന്ത്യയാണ് റിപ്പോർട്ട് ചെയ്തത്. ലോകത്ത് കൊവിഡ് പരീക്ഷണങ്ങളിൽ ഏറ്റവും കൂടുതൽ പ്രതീക്ഷയർപ്പിച്ചിരിക്കുന്ന വാക്സിനാണ് ഓക്സ്ഫഡ്- അസ്ട്രാസെനെകയുടേത്.
 \par ~~~
 'മെഡിസിൻസ് ഹെൽത്ത് റെഗുലേറ്ററി അതോറിറ്റി (എം‌എച്ച്‌ആർ‌എ)യുടെ സ്ഥിരീകരണം ലഭിച്ചതിനെത്തുടർന്ന് ആസ്ട്രാസെനെക ഓക്സ്ഫോർഡ് കൊറോണ വൈറസ് വാക്സിന്‍റെ ക്ലിനിക്കൽ പരീക്ഷണങ്ങൾ യുകെയിൽ പുനരാരംഭിച്ചു.'കമ്പനി പ്രസ്താവനയിലൂടെ പറഞ്ഞു. നേരത്തെ ഓക്സഫഡ് യൂണിവേഴ്സിറ്റി പരീക്ഷണം നിർത്തിവെച്ചതിനു പിന്നാലെ പുനെയിലെ സിറം ഇൻസ്റ്റിറ്റ്യൂട്ടും ഇന്ത്യയിലെ വാക്സിൻ മൂന്നാം ഘട്ട പരീക്ഷണം താല്ക്കാലികമായി നിർത്തി വച്ചിരുന്നു. 

 $$\LARGE x^2+y^2=z^2$$
 \begin{figure}[ht!]
 \centering
  \includegraphics[width=1\textwidth]{editing.jpg}
 \caption{ഷെയർ ചെയ്‌തു സബ്സ്ക്രൈബ് ചെയ്‌തു മറ്റുള്ളവരിലേക്കു എത്തിക്കുക }
 \end{figure}
 
 
 
\section{സ്വർണം }

മൃദുവും തിളക്കമുള്ളതുമായ മഞ്ഞലോഹമാണ് സ്വർണം. വിലയേറിയ ലോഹമായ സ്വർണം, നാണയമായും, ആഭരണങ്ങളുടെ രൂപത്തിലും നൂറ്റാണ്ടുകളായി മനുഷ്യൻ ഉപയോഗിച്ചു പോരുന്നു. 
ചെറിയ കഷണങ്ങളും തരികളുമായി സ്വതന്ത്രാവസ്ഥയിൽത്തന്നെ പ്രകൃതിയിൽ ഈ ലോഹം കണ്ടുവരുന്നു. ലോഹങ്ങളിൽ വച്ച് ഏറ്റവും നന്നായി രൂപഭേദം വരുത്താവുന്ന ലോഹമാണിത്.
\footnote{http://www.webelements.com/webelements/elements/text/Au/key.html "Key properties of gold" (in ഇംഗ്ലീഷ്). ശേഖരിച്ചത് 2007-06-18.}

\section{ഗുണങ്ങൾ}
സ്വർണത്തിന്റെ അണുസംഖ്യ 79-ഉം പ്രതീകം Au എന്നുമാണ്. ഔറം എന്ന ലത്തീൻ വാക്കിൽ നിന്നാണ് Au എന്ന പ്രതീകം ഉണ്ടായത്.
ഏറ്റവും നന്നായി രൂപഭേദം വരുത്താൻ സാധിക്കുന്ന ലോഹമാണ് സ്വർണ്ണം. ഒരു ഗ്രാം സ്വർണ്ണം അടിച്ചു പരത്തി ഒരു ചതുരശ്രമീറ്റർ വിസ്തീർണ്ണമുള്ള ഒരു തകിടാക്കി മാറ്റാൻ സാധിക്കും. 
അതായത് 0.000013 സെന്റീമീറ്റർ വരെ ഇതിന്റെ കനം കുറക്കാൻ കഴിയും. അതു പോലെ വെറും 29 ഗ്രാം സ്വർണ്ണം ഉപയോഗിച്ച് 100 കിലോ മീറ്റർ നീളമുള്ള കമ്പിയുണ്ടാക്കാനും സാധിക്കും. 

\section{ചരിത്രം}
ചരിത്രാതീത കാലം മുതൽക്കേ അറിയപ്പെട്ടിരുന്ന അമൂല്യലോഹമാണ്‌ സ്വർണ്ണം. ഒരുപക്ഷേ മനുഷ്യൻ ആദ്യമായി ഉപയോഗിച്ച ലോഹവും ഇതുതന്നെയായിരിക്കണം.
ബി.സി.ഇ. 2600 ലെ ഈജിപ്ഷ്യൻ ഹീറോഗ്ലിഫിക്സ് ലിഖിതങ്ങളിൽ ഈജിപ്തിൽ സ്വർണ്ണം സുലഭമായിരുന്നെന്ന് പരാമർശിക്കുന്നുണ്ട്.
ചരിത്രം പരിശോധിച്ചാൽ ഈജിപ്തും നുബിയയുമാണ്‌ ലോകത്തിൽ ഏറ്റവുമധികം സ്വർണ്ണം ഉല്പ്പാദിപ്പിച്ചിരുന്ന മേഖലകൾ. ബൈബിളിലെ പഴയ നിയമത്തിൽ സ്വർണ്ണത്തെപ്പറ്റി പലവട്ടം പരാമർശിക്കുന്നുണ്ട്.


\end{document}



